### ISSUE TITLE
con.query issue when entering name index.js:153

### ISSUE THREAD

**Issue by JaNL4U** [nightstudios-net/FiveM-Discord-Bot#1]
![image](https://user-images.githubusercontent.com/68783994/114905886-c156e300-9e19-11eb-88c7-30df1599f6ca.png)

**Comment by nightstudios-net** [comment]
Should be fixed now. Download the files again :)

**Comment by JaNL4U** [comment]
Looks like we have a new error 
![image](https://user-images.githubusercontent.com/68783994/114907195-1f37fa80-9e1b-11eb-9c09-1c715e1206f1.png)
